name: Full-year calendar

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write  # 允许提交文件

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate full-year GitHub calendar
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.isocalendar.fullyear.svg
          token: ${{ secrets.METRIX }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
